version: "3"
services:
  server:
    container_name: pr1_server
    build: ./pr
    volumes:
      - ./pr:/var/www/html
    ports:
      - "8080:80"
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - "./pr/init.sql:/docker-entrypoint-initdb.d/init.sql"
volumes:
 db_volume: